# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.22
  amd64: ghcr.io/home-assistant/amd64-base:3.22
  armhf: ghcr.io/home-assistant/armhf-base:3.22
  armv7: ghcr.io/home-assistant/armv7-base:3.22
  i386: ghcr.io/home-assistant/i386-base:3.22
labels:
  org.opencontainers.image.title: "HA OAuth2 Mail Proxy"
  org.opencontainers.image.description: "Email proxy to allow OAuth2 authentication with IMAP/SMTP calls"
  org.opencontainers.image.source: "https://github.com/nathanfiscus/ha-addons/oauth-mail-proxy"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2021.09.0"
