# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OAuth Mail Proxy
version: "1.0.5"
slug: oauth-mail-proxy
description: Mail proxy to allow OAuth authentication with IMAP/SMTP calls
url: "https://github.com/nathanfiscus/ha-addons/tree/main/oauth-mail-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#image: nathanfiscus/{arch}-addon-oauth-mail-proxy
init: false
map:
  - share:rw
options:
  debug: false
  accounts:
    - email: example@outlook.com
      permission_url: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
      token_url: https://login.microsoftonline.com/common/oauth2/v2.0/token
      oauth2_scope: https://outlook.office.com/IMAP.AccessAsUser.All https://outlook.office.com/POP.AccessAsUser.All https://outlook.office.com/SMTP.Send offline_access
      redirect_uri: http://localhost
      client_id: "*** your client id here ***"
      client_secret: "*** your client secret here (remove this entire line if a secret is not required) ***"
ports:
  1993/tcp: 1993
  8080/tcp: 8080
schema:
  debug: bool
  accounts:
    - email: str
      permission_url: str
      token_url: str
      oauth2_scope: str
      redirect_uri: str
      client_id: str
      client_secret: "str?"
