# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: OAuth Mail Proxy
version: "1.1.1"
slug: oauth-mail-proxy
description: Mail proxy to allow OAuth authentication with IMAP/SMTP calls
url: "https://github.com/nathanfiscus/ha-addons/tree/main/oauth-mail-proxy"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
#image: nathanfiscus/{arch}-addon-oauth-mail-proxy
init: false
map:
  - share:rw
options:
  local_auth: false
  debug: false
ports:
  1993/tcp: 1993
  8080/tcp: 8080
schema:
  local_auth: bool
  debug: bool
